
# This Makefile is part of MOSSCO
#
# Do not edit this file, it is automatically generated by
# the call python @todo @todo
#
# @copyright Copyright (C) 2017 Helmholtz-Zentrum Geesthacht
# @author Carsten Lemmen, <carsten.lemmen@hzg.de>

#
# MOSSCO is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License v3+.  MOSSCO is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY.  Consult the file
# LICENSE.GPL or www.gnu.org/licenses/gpl-3.0.txt for the full license terms.
#
TARGETS += libmossco_calculator
LIBS_TO_CLEAN += libmossco_calculator.a

libmossco_calculator: prefix $(MOSSCO_LIBRARY_PATH)/libmossco_calculator.a(calculator.o)
