# This travis configuration file is part of MOSSCO
#
# @copyright (C) 2017 Helmholtz-Zentrum Geesthacht
# @author Carsten Lemmen, Helmholtz-Zentrum Geesthacht
#
# MOSSCO is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License v3+.  MOSSCO is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY.  Consult the file
# LICENSE.GPL or www.gnu.org/licenses/gpl-3.0.txt for the full license terms.

language: c # There is no Fortran support yet in travis, so we emulate it

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

git:
  depth: 3

# @todo, add other branches, foremost master once travis is merged into master
branches:
  only: travis

# A list of trusty packages is provided at https://packages.ubuntu.com/trusty/allpackages?format=txt.gz
addons:
  apt:
    packages:
    - gfortran
    - libnetcdf-dev
    - libnetcdfc7
    - libnetcdff5
    - binutils
    - cmake
    - doxygen
    - openmpi-bin
    - openmpi-common
    - libmpich-dev
    - mpich
    - python2.7
    - python-yaml

before_script:
- export DEPS=${TRAVIS_BUILD_DIR}/../dependencies
- export NETCDF_VERSION=NETCDF4
- export ESMFMKFILE
- export ESMF_DIR=${TRAVIS_BUILD_DIR}/esmf
- export COMMS="openmpi"
- export COMPS="gfortran"
- mkdir -p ${DEPS}
- ./scripts/installation/install_esmf_versions.sh ${DEPS}

script:
- export MOSSCO_DIR=${TRAVIS_BUILD_DIR}
- make external
- make all
