language: c # Fortran is not recognized, so use C here

python:
  - 2.7

dist: trusty
sudo: false

cache:
  - brew: true
  - pip: true
  - apt: true

addons:
  pip:
    - numpy
    - basemap
    - netCDF4

  apt:
    packages:
      - gfortran
      - clang
      - libopenmpi-dev
      - libnetcdff5
      - libnetcdf-dev
      - libnetcdfc7
      - python-netcdf
      - doxygen
      - libxerces-c-dev

os:
  - linux
#  - osx

#osx_image: xcode9.3beta

before_install:
  # - brew update
  # - brew install netcdf
  # - brew install json-fortran
  # - brew install doxygen

notifications:
  email: true

env:
  global:
    - MOSSCO_FFLAGS="-g -Wall -fprofile-arcs -ftest-coverage -O0"
    - MOSSCO_DIR=${TRAVIS_BUILD_DIR}
    - ESMF_INSTALL_PREFIX=${HOME/opt/esmf}
    - ESMF_DIR=${HOME/opt/src/esmf}

install:
  - bash ${MOSSCO_DIR}/scripts/installation/install_esmf_versions.sh
  - make external
  - make libfabm_external
  - make libgotm_external
  - make libgetm_external
  - make all

#deploy:
#  - mkdir -p ${HOME}/opt/bin
#  - ln -sf ${MOSSCO_DIR}/scripts/mossco.sh ${HOME}/opt/bin/mossco
