language: c # Fortran is not recognized, so use C here

python:
  - 2.7

sudo: true

cache:
  brew: true
  pip: true

addons:
  pip:
    - numpy
    - basemap
    - netCDF4

os:
#  - linux
  - osx

osx_image: xcode9.3beta

before_install:
  - brew update
  - brew install netcdf
  - brew install json-fortran
  - brew install doxygen


notifications:
  email: true

env:
  global:
    - MOSSCO_FFLAGS="-g -Wall -fprofile-arcs -ftest-coverage -O0"
    - MOSSCO_DIR=${TRAVIS_BUILD_DIR}
  matrix:
      # CMake build with unit tests, no documentation, with coverage analysis
      # No unicode so that coverage combined with the build script will cover unicode
      # and non-unicode code paths
    - make external
    - make libfabm_external
    - make libgotm_external
    - >
      make -j 4 all

install:
  - mkdir -p ${HOME}/opt/bin
  - ln -sf ${MOSSCO_DIR}/scripts/mossco.sh ${HOME}/opt/bin/mossco
