# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/uwhpsc/baw/nc_info/lib/project_dlg/gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(652, 535)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem, 5, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab_1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_8.addWidget(self.line_2, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab_1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_8.addWidget(self.line, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_32 = QtGui.QLabel(self.tab_1)
        self.label_32.setMinimumSize(QtCore.QSize(100, 0))
        self.label_32.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_7.addWidget(self.label_32)
        self.comboBox_projectionResolution = QtGui.QComboBox(self.tab_1)
        self.comboBox_projectionResolution.setObjectName(_fromUtf8("comboBox_projectionResolution"))
        self.horizontalLayout_7.addWidget(self.comboBox_projectionResolution)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label = QtGui.QLabel(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.comboBox_selectProjection = QtGui.QComboBox(self.tab_1)
        self.comboBox_selectProjection.setObjectName(_fromUtf8("comboBox_selectProjection"))
        self.horizontalLayout_6.addWidget(self.comboBox_selectProjection)
        self.gridLayout_8.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox_drawCoasline = QtGui.QCheckBox(self.tab_1)
        self.checkBox_drawCoasline.setChecked(True)
        self.checkBox_drawCoasline.setObjectName(_fromUtf8("checkBox_drawCoasline"))
        self.horizontalLayout_4.addWidget(self.checkBox_drawCoasline)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_drawRiver = QtGui.QCheckBox(self.tab_1)
        self.checkBox_drawRiver.setChecked(True)
        self.checkBox_drawRiver.setObjectName(_fromUtf8("checkBox_drawRiver"))
        self.horizontalLayout.addWidget(self.checkBox_drawRiver)
        self.frame_fillRiverColor = QtGui.QFrame(self.tab_1)
        self.frame_fillRiverColor.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_fillRiverColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_fillRiverColor.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_fillRiverColor.setObjectName(_fromUtf8("frame_fillRiverColor"))
        self.horizontalLayout.addWidget(self.frame_fillRiverColor)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBox_fillContinent = QtGui.QCheckBox(self.tab_1)
        self.checkBox_fillContinent.setChecked(True)
        self.checkBox_fillContinent.setObjectName(_fromUtf8("checkBox_fillContinent"))
        self.horizontalLayout_3.addWidget(self.checkBox_fillContinent)
        self.frame_fillContinentColor = QtGui.QFrame(self.tab_1)
        self.frame_fillContinentColor.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_fillContinentColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_fillContinentColor.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_fillContinentColor.setObjectName(_fromUtf8("frame_fillContinentColor"))
        self.horizontalLayout_3.addWidget(self.frame_fillContinentColor)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox_fillOcean = QtGui.QCheckBox(self.tab_1)
        self.checkBox_fillOcean.setChecked(True)
        self.checkBox_fillOcean.setObjectName(_fromUtf8("checkBox_fillOcean"))
        self.horizontalLayout_2.addWidget(self.checkBox_fillOcean)
        self.frame_fillOceanColor = QtGui.QFrame(self.tab_1)
        self.frame_fillOceanColor.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_fillOceanColor.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_fillOceanColor.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_fillOceanColor.setObjectName(_fromUtf8("frame_fillOceanColor"))
        self.horizontalLayout_2.addWidget(self.frame_fillOceanColor)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_project_Kwargs1 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_project_Kwargs1.setFlat(False)
        self.groupBox_project_Kwargs1.setCheckable(False)
        self.groupBox_project_Kwargs1.setObjectName(_fromUtf8("groupBox_project_Kwargs1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_project_Kwargs1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_project_Kwargs1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_llcrnrlon = QtGui.QLineEdit(self.groupBox_project_Kwargs1)
        self.lineEdit_llcrnrlon.setObjectName(_fromUtf8("lineEdit_llcrnrlon"))
        self.gridLayout_2.addWidget(self.lineEdit_llcrnrlon, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_project_Kwargs1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_llcrnrlat = QtGui.QLineEdit(self.groupBox_project_Kwargs1)
        self.lineEdit_llcrnrlat.setObjectName(_fromUtf8("lineEdit_llcrnrlat"))
        self.gridLayout_2.addWidget(self.lineEdit_llcrnrlat, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_project_Kwargs1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_urcrnrlon = QtGui.QLineEdit(self.groupBox_project_Kwargs1)
        self.lineEdit_urcrnrlon.setObjectName(_fromUtf8("lineEdit_urcrnrlon"))
        self.gridLayout_2.addWidget(self.lineEdit_urcrnrlon, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_project_Kwargs1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_urcrnrlat = QtGui.QLineEdit(self.groupBox_project_Kwargs1)
        self.lineEdit_urcrnrlat.setObjectName(_fromUtf8("lineEdit_urcrnrlat"))
        self.gridLayout_2.addWidget(self.lineEdit_urcrnrlat, 3, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_project_Kwargs1)
        self.groupBox_project_Kwargs2 = QtGui.QGroupBox(self.tab_1)
        self.groupBox_project_Kwargs2.setFlat(False)
        self.groupBox_project_Kwargs2.setCheckable(False)
        self.groupBox_project_Kwargs2.setChecked(False)
        self.groupBox_project_Kwargs2.setObjectName(_fromUtf8("groupBox_project_Kwargs2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_project_Kwargs2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_project_Kwargs2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_width = QtGui.QLineEdit(self.groupBox_project_Kwargs2)
        self.lineEdit_width.setObjectName(_fromUtf8("lineEdit_width"))
        self.gridLayout.addWidget(self.lineEdit_width, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_project_Kwargs2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_height = QtGui.QLineEdit(self.groupBox_project_Kwargs2)
        self.lineEdit_height.setObjectName(_fromUtf8("lineEdit_height"))
        self.gridLayout.addWidget(self.lineEdit_height, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_project_Kwargs2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_lon0 = QtGui.QLineEdit(self.groupBox_project_Kwargs2)
        self.lineEdit_lon0.setObjectName(_fromUtf8("lineEdit_lon0"))
        self.gridLayout.addWidget(self.lineEdit_lon0, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_project_Kwargs2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEdit_lat0 = QtGui.QLineEdit(self.groupBox_project_Kwargs2)
        self.lineEdit_lat0.setObjectName(_fromUtf8("lineEdit_lat0"))
        self.gridLayout.addWidget(self.lineEdit_lat0, 3, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_project_Kwargs2)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.line.raise_()
        self.line_2.raise_()
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_parallels = QtGui.QGroupBox(self.tab_2)
        self.groupBox_parallels.setCheckable(True)
        self.groupBox_parallels.setChecked(False)
        self.groupBox_parallels.setObjectName(_fromUtf8("groupBox_parallels"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_parallels)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_20 = QtGui.QLabel(self.groupBox_parallels)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_7.addWidget(self.label_20, 0, 0, 1, 1)
        self.lineEdit_par_range = QtGui.QLineEdit(self.groupBox_parallels)
        self.lineEdit_par_range.setObjectName(_fromUtf8("lineEdit_par_range"))
        self.gridLayout_7.addWidget(self.lineEdit_par_range, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 3, 1, 1)
        self.pushButton_par_color = QtGui.QPushButton(self.groupBox_parallels)
        self.pushButton_par_color.setObjectName(_fromUtf8("pushButton_par_color"))
        self.gridLayout_7.addWidget(self.pushButton_par_color, 1, 0, 1, 1)
        self.frame_par_color = QtGui.QFrame(self.groupBox_parallels)
        self.frame_par_color.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_par_color.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_par_color.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_par_color.setObjectName(_fromUtf8("frame_par_color"))
        self.gridLayout_7.addWidget(self.frame_par_color, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_parallels)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_7.addWidget(self.label_21, 1, 2, 1, 1)
        self.lineEdit_par_zorder = QtGui.QLineEdit(self.groupBox_parallels)
        self.lineEdit_par_zorder.setObjectName(_fromUtf8("lineEdit_par_zorder"))
        self.gridLayout_7.addWidget(self.lineEdit_par_zorder, 1, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_parallels)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_7.addWidget(self.label_22, 2, 0, 1, 1)
        self.lineEdit_par_linewidth = QtGui.QLineEdit(self.groupBox_parallels)
        self.lineEdit_par_linewidth.setObjectName(_fromUtf8("lineEdit_par_linewidth"))
        self.gridLayout_7.addWidget(self.lineEdit_par_linewidth, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_parallels)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_7.addWidget(self.label_23, 2, 2, 1, 1)
        self.lineEdit_par_labels = QtGui.QLineEdit(self.groupBox_parallels)
        self.lineEdit_par_labels.setObjectName(_fromUtf8("lineEdit_par_labels"))
        self.gridLayout_7.addWidget(self.lineEdit_par_labels, 2, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_parallels)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_7.addWidget(self.label_24, 3, 0, 1, 1)
        self.lineEdit_par_dashes = QtGui.QLineEdit(self.groupBox_parallels)
        self.lineEdit_par_dashes.setObjectName(_fromUtf8("lineEdit_par_dashes"))
        self.gridLayout_7.addWidget(self.lineEdit_par_dashes, 3, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_parallels)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 3, 2, 1, 1)
        self.lineEdit_par_fmt = QtGui.QLineEdit(self.groupBox_parallels)
        self.lineEdit_par_fmt.setObjectName(_fromUtf8("lineEdit_par_fmt"))
        self.gridLayout_7.addWidget(self.lineEdit_par_fmt, 3, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_parallels, 1, 0, 1, 1)
        self.groupBox_meridians = QtGui.QGroupBox(self.tab_2)
        self.groupBox_meridians.setCheckable(True)
        self.groupBox_meridians.setChecked(False)
        self.groupBox_meridians.setObjectName(_fromUtf8("groupBox_meridians"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_meridians)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_14 = QtGui.QLabel(self.groupBox_meridians)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineEdit_mer_range = QtGui.QLineEdit(self.groupBox_meridians)
        self.lineEdit_mer_range.setObjectName(_fromUtf8("lineEdit_mer_range"))
        self.gridLayout_5.addWidget(self.lineEdit_mer_range, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(130, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 3, 1, 1)
        self.pushButton_mer_color = QtGui.QPushButton(self.groupBox_meridians)
        self.pushButton_mer_color.setObjectName(_fromUtf8("pushButton_mer_color"))
        self.gridLayout_5.addWidget(self.pushButton_mer_color, 1, 0, 1, 1)
        self.frame_mer_color = QtGui.QFrame(self.groupBox_meridians)
        self.frame_mer_color.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_mer_color.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_mer_color.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_mer_color.setObjectName(_fromUtf8("frame_mer_color"))
        self.gridLayout_5.addWidget(self.frame_mer_color, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_meridians)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 1, 2, 1, 1)
        self.lineEdit_mer_zorder = QtGui.QLineEdit(self.groupBox_meridians)
        self.lineEdit_mer_zorder.setObjectName(_fromUtf8("lineEdit_mer_zorder"))
        self.gridLayout_5.addWidget(self.lineEdit_mer_zorder, 1, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_meridians)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 2, 0, 1, 1)
        self.lineEdit_mer_linewidth = QtGui.QLineEdit(self.groupBox_meridians)
        self.lineEdit_mer_linewidth.setObjectName(_fromUtf8("lineEdit_mer_linewidth"))
        self.gridLayout_5.addWidget(self.lineEdit_mer_linewidth, 2, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_meridians)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 2, 2, 1, 1)
        self.lineEdit_mer_labels = QtGui.QLineEdit(self.groupBox_meridians)
        self.lineEdit_mer_labels.setObjectName(_fromUtf8("lineEdit_mer_labels"))
        self.gridLayout_5.addWidget(self.lineEdit_mer_labels, 2, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_meridians)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 3, 0, 1, 1)
        self.lineEdit_mer_dashes = QtGui.QLineEdit(self.groupBox_meridians)
        self.lineEdit_mer_dashes.setObjectName(_fromUtf8("lineEdit_mer_dashes"))
        self.gridLayout_5.addWidget(self.lineEdit_mer_dashes, 3, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_meridians)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_5.addWidget(self.label_19, 3, 2, 1, 1)
        self.lineEdit_mer_fmt = QtGui.QLineEdit(self.groupBox_meridians)
        self.lineEdit_mer_fmt.setObjectName(_fromUtf8("lineEdit_mer_fmt"))
        self.gridLayout_5.addWidget(self.lineEdit_mer_fmt, 3, 3, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_meridians, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.groupBox_contour = QtGui.QGroupBox(self.tab_3)
        self.groupBox_contour.setCheckable(True)
        self.groupBox_contour.setChecked(False)
        self.groupBox_contour.setObjectName(_fromUtf8("groupBox_contour"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_contour)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_contour_fill = QtGui.QCheckBox(self.groupBox_contour)
        self.checkBox_contour_fill.setObjectName(_fromUtf8("checkBox_contour_fill"))
        self.gridLayout_4.addWidget(self.checkBox_contour_fill, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(84, 12, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_contour)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit_contour_range = QtGui.QLineEdit(self.groupBox_contour)
        self.lineEdit_contour_range.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_contour_range.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_contour_range.setObjectName(_fromUtf8("lineEdit_contour_range"))
        self.gridLayout_4.addWidget(self.lineEdit_contour_range, 1, 1, 1, 1)
        self.checkBox_contour_label = QtGui.QCheckBox(self.groupBox_contour)
        self.checkBox_contour_label.setObjectName(_fromUtf8("checkBox_contour_label"))
        self.gridLayout_4.addWidget(self.checkBox_contour_label, 2, 0, 1, 1)
        self.checkBox_contour_label_inline = QtGui.QCheckBox(self.groupBox_contour)
        self.checkBox_contour_label_inline.setEnabled(False)
        self.checkBox_contour_label_inline.setObjectName(_fromUtf8("checkBox_contour_label_inline"))
        self.gridLayout_4.addWidget(self.checkBox_contour_label_inline, 2, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_contour)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_contour_lable_fmt = QtGui.QLineEdit(self.groupBox_contour)
        self.lineEdit_contour_lable_fmt.setEnabled(False)
        self.lineEdit_contour_lable_fmt.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_contour_lable_fmt.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_contour_lable_fmt.setObjectName(_fromUtf8("lineEdit_contour_lable_fmt"))
        self.gridLayout_4.addWidget(self.lineEdit_contour_lable_fmt, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_contour)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 4, 0, 1, 1)
        self.lineEdit_contour_label_fntsize = QtGui.QLineEdit(self.groupBox_contour)
        self.lineEdit_contour_label_fntsize.setEnabled(False)
        self.lineEdit_contour_label_fntsize.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_contour_label_fntsize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_contour_label_fntsize.setObjectName(_fromUtf8("lineEdit_contour_label_fntsize"))
        self.gridLayout_4.addWidget(self.lineEdit_contour_label_fntsize, 4, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_contour, 1, 0, 1, 1)
        self.groupBox_scale = QtGui.QGroupBox(self.tab_3)
        self.groupBox_scale.setEnabled(True)
        self.groupBox_scale.setCheckable(True)
        self.groupBox_scale.setChecked(False)
        self.groupBox_scale.setObjectName(_fromUtf8("groupBox_scale"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_scale)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_36 = QtGui.QLabel(self.groupBox_scale)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_12.addWidget(self.label_36, 2, 2, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_scale)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_12.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_scale)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_12.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_scale)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_12.addWidget(self.label_34, 1, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_scale)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_12.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_30 = QtGui.QLabel(self.groupBox_scale)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_12.addWidget(self.label_30, 0, 2, 1, 1)
        self.lineEdit_scale_lat = QtGui.QLineEdit(self.groupBox_scale)
        self.lineEdit_scale_lat.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_scale_lat.setObjectName(_fromUtf8("lineEdit_scale_lat"))
        self.gridLayout_12.addWidget(self.lineEdit_scale_lat, 0, 3, 1, 1)
        self.lineEdit_scale_length = QtGui.QLineEdit(self.groupBox_scale)
        self.lineEdit_scale_length.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_scale_length.setObjectName(_fromUtf8("lineEdit_scale_length"))
        self.gridLayout_12.addWidget(self.lineEdit_scale_length, 1, 1, 1, 1)
        self.lineEdit_scale_lon = QtGui.QLineEdit(self.groupBox_scale)
        self.lineEdit_scale_lon.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_scale_lon.setObjectName(_fromUtf8("lineEdit_scale_lon"))
        self.gridLayout_12.addWidget(self.lineEdit_scale_lon, 0, 1, 1, 1)
        self.lineEdit_scale_units = QtGui.QLineEdit(self.groupBox_scale)
        self.lineEdit_scale_units.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_scale_units.setObjectName(_fromUtf8("lineEdit_scale_units"))
        self.gridLayout_12.addWidget(self.lineEdit_scale_units, 1, 3, 1, 1)
        self.lineEdit_scale_fontsize = QtGui.QLineEdit(self.groupBox_scale)
        self.lineEdit_scale_fontsize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_scale_fontsize.setObjectName(_fromUtf8("lineEdit_scale_fontsize"))
        self.gridLayout_12.addWidget(self.lineEdit_scale_fontsize, 2, 1, 1, 1)
        self.lineEdit_scale_fmt = QtGui.QLineEdit(self.groupBox_scale)
        self.lineEdit_scale_fmt.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_scale_fmt.setObjectName(_fromUtf8("lineEdit_scale_fmt"))
        self.gridLayout_12.addWidget(self.lineEdit_scale_fmt, 2, 3, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_scale, 2, 0, 1, 1)
        self.groupBox_cbar = QtGui.QGroupBox(self.tab_3)
        self.groupBox_cbar.setCheckable(True)
        self.groupBox_cbar.setObjectName(_fromUtf8("groupBox_cbar"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_cbar)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_26 = QtGui.QLabel(self.groupBox_cbar)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_11.addWidget(self.label_26, 0, 0, 1, 1)
        self.comboBox_cbar_loc = QtGui.QComboBox(self.groupBox_cbar)
        self.comboBox_cbar_loc.setObjectName(_fromUtf8("comboBox_cbar_loc"))
        self.gridLayout_11.addWidget(self.comboBox_cbar_loc, 0, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_cbar)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_11.addWidget(self.label_27, 1, 0, 1, 1)
        self.lineEdit_cbar_size = QtGui.QLineEdit(self.groupBox_cbar)
        self.lineEdit_cbar_size.setObjectName(_fromUtf8("lineEdit_cbar_size"))
        self.gridLayout_11.addWidget(self.lineEdit_cbar_size, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_cbar)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_11.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_cbar_pad = QtGui.QLineEdit(self.groupBox_cbar)
        self.lineEdit_cbar_pad.setObjectName(_fromUtf8("lineEdit_cbar_pad"))
        self.gridLayout_11.addWidget(self.lineEdit_cbar_pad, 2, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_cbar)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_11.addWidget(self.label_33, 3, 0, 1, 1)
        self.lineEdit_cbar_label = QtGui.QLineEdit(self.groupBox_cbar)
        self.lineEdit_cbar_label.setObjectName(_fromUtf8("lineEdit_cbar_label"))
        self.gridLayout_11.addWidget(self.lineEdit_cbar_label, 3, 1, 1, 1)
        self.checkBox_cbar_addcontourlines = QtGui.QCheckBox(self.groupBox_cbar)
        self.checkBox_cbar_addcontourlines.setEnabled(False)
        self.checkBox_cbar_addcontourlines.setObjectName(_fromUtf8("checkBox_cbar_addcontourlines"))
        self.gridLayout_11.addWidget(self.checkBox_cbar_addcontourlines, 4, 0, 1, 2)
        self.gridLayout_10.addWidget(self.groupBox_cbar, 1, 2, 2, 1)
        spacerItem6 = QtGui.QSpacerItem(325, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem6, 0, 2, 1, 1)
        self.checkBox_pcolormesh = QtGui.QCheckBox(self.tab_3)
        self.checkBox_pcolormesh.setChecked(True)
        self.checkBox_pcolormesh.setObjectName(_fromUtf8("checkBox_pcolormesh"))
        self.gridLayout_10.addWidget(self.checkBox_pcolormesh, 0, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem7, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textEdit = QtGui.QTextEdit(self.tab_4)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_6.addWidget(self.textEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.pushButton_run = QtGui.QPushButton(Dialog)
        self.pushButton_run.setObjectName(_fromUtf8("pushButton_run"))
        self.horizontalLayout_8.addWidget(self.pushButton_run)
        self.pushButton_gen = QtGui.QPushButton(Dialog)
        self.pushButton_gen.setObjectName(_fromUtf8("pushButton_gen"))
        self.horizontalLayout_8.addWidget(self.pushButton_gen)
        self.pushButton_cancel = QtGui.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_8.addWidget(self.pushButton_cancel)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_32.setText(_translate("Dialog", "Resolution", None))
        self.label.setText(_translate("Dialog", "Projection", None))
        self.checkBox_drawCoasline.setText(_translate("Dialog", "Draw Coastlines", None))
        self.checkBox_drawRiver.setText(_translate("Dialog", "Draw Rivers", None))
        self.checkBox_fillContinent.setText(_translate("Dialog", "Fill Continents", None))
        self.checkBox_fillOcean.setText(_translate("Dialog", "Fill Oceans", None))
        self.groupBox_project_Kwargs1.setTitle(_translate("Dialog", "Option 1", None))
        self.label_2.setText(_translate("Dialog", "llcrnrlon", None))
        self.lineEdit_llcrnrlon.setText(_translate("Dialog", "0", None))
        self.label_3.setText(_translate("Dialog", "llcrnrlat", None))
        self.lineEdit_llcrnrlat.setText(_translate("Dialog", "0", None))
        self.label_4.setText(_translate("Dialog", "urcrnrlon", None))
        self.lineEdit_urcrnrlon.setText(_translate("Dialog", "10", None))
        self.label_5.setText(_translate("Dialog", "urcrnrlat", None))
        self.lineEdit_urcrnrlat.setText(_translate("Dialog", "10", None))
        self.groupBox_project_Kwargs2.setTitle(_translate("Dialog", "Option 2", None))
        self.label_7.setText(_translate("Dialog", "width", None))
        self.label_8.setText(_translate("Dialog", "height", None))
        self.label_6.setText(_translate("Dialog", "lon_0", None))
        self.label_9.setText(_translate("Dialog", "lat_0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Projection", None))
        self.groupBox_parallels.setTitle(_translate("Dialog", "Parallels", None))
        self.label_20.setText(_translate("Dialog", "Range", None))
        self.lineEdit_par_range.setText(_translate("Dialog", "-90, 100, 10", None))
        self.pushButton_par_color.setText(_translate("Dialog", "Color", None))
        self.label_21.setText(_translate("Dialog", "zorder", None))
        self.lineEdit_par_zorder.setText(_translate("Dialog", "None", None))
        self.label_22.setText(_translate("Dialog", "Linewidth", None))
        self.lineEdit_par_linewidth.setText(_translate("Dialog", "1.0", None))
        self.label_23.setText(_translate("Dialog", "Labels", None))
        self.lineEdit_par_labels.setText(_translate("Dialog", "0, 0, 0, 0", None))
        self.label_24.setText(_translate("Dialog", "Dashes", None))
        self.lineEdit_par_dashes.setText(_translate("Dialog", "1, 1", None))
        self.label_25.setText(_translate("Dialog", "format", None))
        self.lineEdit_par_fmt.setText(_translate("Dialog", "%g", None))
        self.groupBox_meridians.setTitle(_translate("Dialog", "Meridians", None))
        self.label_14.setText(_translate("Dialog", "Range", None))
        self.lineEdit_mer_range.setText(_translate("Dialog", "0, 380, 20", None))
        self.pushButton_mer_color.setText(_translate("Dialog", "Color", None))
        self.label_17.setText(_translate("Dialog", "zorder", None))
        self.lineEdit_mer_zorder.setText(_translate("Dialog", "None", None))
        self.label_15.setText(_translate("Dialog", "Linewidth", None))
        self.lineEdit_mer_linewidth.setText(_translate("Dialog", "1.0", None))
        self.label_18.setText(_translate("Dialog", "Labels", None))
        self.lineEdit_mer_labels.setText(_translate("Dialog", "0, 0, 0, 0", None))
        self.label_16.setText(_translate("Dialog", "Dashes", None))
        self.lineEdit_mer_dashes.setText(_translate("Dialog", "1, 1", None))
        self.label_19.setText(_translate("Dialog", "format", None))
        self.lineEdit_mer_fmt.setText(_translate("Dialog", "%g", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Meridians/Parallels", None))
        self.groupBox_contour.setTitle(_translate("Dialog", "Contour", None))
        self.checkBox_contour_fill.setText(_translate("Dialog", "Fill", None))
        self.label_11.setText(_translate("Dialog", "Range", None))
        self.checkBox_contour_label.setText(_translate("Dialog", "Label", None))
        self.checkBox_contour_label_inline.setText(_translate("Dialog", "Inline", None))
        self.label_12.setText(_translate("Dialog", "fmt", None))
        self.lineEdit_contour_lable_fmt.setText(_translate("Dialog", "%d", None))
        self.label_13.setText(_translate("Dialog", "font size", None))
        self.lineEdit_contour_label_fntsize.setText(_translate("Dialog", "12", None))
        self.groupBox_scale.setTitle(_translate("Dialog", "Draw map scale", None))
        self.label_36.setText(_translate("Dialog", "fmt", None))
        self.label_35.setText(_translate("Dialog", "font size", None))
        self.label_29.setText(_translate("Dialog", "lon", None))
        self.label_34.setText(_translate("Dialog", "units", None))
        self.label_31.setText(_translate("Dialog", "length", None))
        self.label_30.setText(_translate("Dialog", "lat", None))
        self.lineEdit_scale_length.setText(_translate("Dialog", "100", None))
        self.lineEdit_scale_units.setText(_translate("Dialog", "km", None))
        self.lineEdit_scale_fontsize.setText(_translate("Dialog", "9.", None))
        self.lineEdit_scale_fmt.setText(_translate("Dialog", "%d", None))
        self.groupBox_cbar.setTitle(_translate("Dialog", "Colorbar", None))
        self.label_26.setText(_translate("Dialog", "Location", None))
        self.label_27.setText(_translate("Dialog", "Size", None))
        self.lineEdit_cbar_size.setText(_translate("Dialog", "5%", None))
        self.label_28.setText(_translate("Dialog", "Pad", None))
        self.lineEdit_cbar_pad.setText(_translate("Dialog", "2%", None))
        self.label_33.setText(_translate("Dialog", "Label", None))
        self.lineEdit_cbar_label.setText(_translate("Dialog", "your data label", None))
        self.checkBox_cbar_addcontourlines.setText(_translate("Dialog", "Add contour lines", None))
        self.checkBox_pcolormesh.setText(_translate("Dialog", "Colormesh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Plot type", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Script", None))
        self.pushButton_run.setText(_translate("Dialog", "Run script (Plot)", None))
        self.pushButton_gen.setText(_translate("Dialog", "Generate Script", None))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel", None))

