!> @brief Implementation of an ESMF toplevel coupling
!>
!> Do not edit this file, it is automatically generated by
!> the call 'python ./create_coupling.py reference_3d.yaml'
!>
!> This computer program is part of MOSSCO.
!> @copyright Copyright (C) 2014, Helmholtz-Zentrum Geesthacht
!> @author Carsten Lemmen, <carsten.lemmen@hzg.de>

!
! MOSSCO is free software: you can redistribute it and/or modify it under the
! terms of the GNU General Public License v3+.  MOSSCO is distributed in the
! hope that it will be useful, but WITHOUT ANY WARRANTY.  Consult the file
! LICENSE.GPL or www.gnu.org/licenses/gpl-3.0.txt for the full license terms.
!
module toplevel_component

  use esmf
  use mossco_variable_types
  use mossco_state
  use mossco_component

  use getm_component, only : getm_SetServices => SetServices 
  use fabm_pelagic_component, only : fabm_pelagic_SetServices => SetServices 
  use erosed_component, only : erosed_SetServices => SetServices 
  use constant_component, only : constant_SetServices => SetServices 
  use fabm_sediment_component, only : fabm_sediment_SetServices => SetServices 
  use simplewave_component, only : simplewave_SetServices => SetServices 
  use netcdf_component, only : netcdf_SetServices => SetServices 
  use clm_netcdf_component, only : clm_netcdf_SetServices => SetServices 
  use benthos_component, only : benthos_SetServices => SetServices 
  use link_coupler, only : link_coupler_SetServices => SetServices 
  use benthic_pelagic_coupler, only : benthic_pelagic_coupler_SetServices => SetServices 
  use pelagic_benthic_coupler, only : pelagic_benthic_coupler_SetServices => SetServices 

  implicit none

  private

  public SetServices

  type(ESMF_GridComp),dimension(:),save, allocatable :: gridCompList
  type(ESMF_CplComp),dimension(:), save, allocatable :: cplCompList
  type(ESMF_State), dimension(:),  save, allocatable :: exportStates, importStates
  type(ESMF_Alarm), dimension(:),  save, allocatable :: cplAlarmList
  type(ESMF_Clock), dimension(:),  save, allocatable :: gridCompClockList
  character(len=ESMF_MAXSTR), dimension(:), save, allocatable :: gridCompNames
  character(len=ESMF_MAXSTR), dimension(:), save, allocatable :: cplCompNames
  character(len=ESMF_MAXSTR), dimension(:), save, allocatable :: cplNames
  type(ESMF_CplComp), save  :: link_couplerComp
  type(ESMF_CplComp), save  :: benthic_pelagic_couplerComp
  type(ESMF_CplComp), save  :: pelagic_benthic_couplerComp
  type(ESMF_GridComp), save :: getmComp
  type(ESMF_GridComp), save :: fabm_pelagicComp
  type(ESMF_GridComp), save :: erosedComp
  type(ESMF_GridComp), save :: constantComp
  type(ESMF_GridComp), save :: fabm_sedimentComp
  type(ESMF_GridComp), save :: simplewaveComp
  type(ESMF_GridComp), save :: netcdfComp
  type(ESMF_GridComp), save :: clm_netcdfComp
  type(ESMF_GridComp), save :: benthosComp
  type(ESMF_State), save    :: getmExportState, getmImportState
  type(ESMF_State), save    :: fabm_pelagicExportState, fabm_pelagicImportState
  type(ESMF_State), save    :: erosedExportState, erosedImportState
  type(ESMF_State), save    :: constantExportState, constantImportState
  type(ESMF_State), save    :: fabm_sedimentExportState, fabm_sedimentImportState
  type(ESMF_State), save    :: simplewaveExportState, simplewaveImportState
  type(ESMF_State), save    :: netcdfExportState, netcdfImportState
  type(ESMF_State), save    :: clm_netcdfExportState, clm_netcdfImportState
  type(ESMF_State), save    :: benthosExportState, benthosImportState


  contains

  !> Provide an ESMF compliant SetServices routine, which defines
  !! entry points for Init/Run/Finalize
  subroutine SetServices(gridcomp, rc)

    type(ESMF_GridComp)  :: gridcomp
    integer, intent(out) :: rc

    rc = ESMF_SUCCESS

    call ESMF_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_INITIALIZE, Initialize, rc=rc)
    if(rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
    call ESMF_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_RUN, Run, rc=rc)
    if(rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
    call ESMF_GridCompSetEntryPoint(gridcomp, ESMF_METHOD_FINALIZE, Finalize, rc=rc)
    if(rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  end subroutine SetServices

  !> Initialize the coupling
  !!
  subroutine Initialize(gridComp, importState, exportState, parentClock, rc)

    implicit none

    type(ESMF_GridComp)  :: gridComp
    type(ESMF_State)     :: importState, exportState
    type(ESMF_Clock)     :: parentClock
    integer, intent(out) :: rc

    character(len=19)       :: timestring
    type(ESMF_Time)         :: clockTime, startTime, stopTime, currTime
    type(ESMF_Time)         :: ringTime, time
    type(ESMF_TimeInterval) :: timeInterval, timeStep, alarmInterval
    real(ESMF_KIND_R8)      :: dt

    integer(ESMF_KIND_I4)  :: numGridComp, numCplComp, petCount
    integer(ESMF_KIND_I4)  :: alarmCount, numCplAlarm, i
    type(ESMF_Alarm), dimension(:), allocatable :: alarmList !> @todo shoudl this be a pointer?
    character(ESMF_MAXSTR) :: name, message
    type(ESMF_Alarm)       :: childAlarm
    type(ESMF_Clock)       :: childClock
    type(ESMF_Clock)       :: clock !> This component's internal clock
    logical                :: clockIsPresent
    integer(ESMF_KIND_I4), allocatable :: petList(:)
    type(ESMF_VM)          :: vm

    integer(ESMF_KIND_I4)  :: phase, phaseCount
    integer(ESMF_KIND_I4), dimension(:), allocatable :: phaseCountList
    logical, allocatable   :: hasPhaseZeroList(:)
    logical                :: hasPhaseZero
    integer(ESMF_KIND_I4), parameter :: maxPhaseCount=9

    rc = ESMF_SUCCESS

    call MOSSCO_CompEntry(gridComp, parentClock, name, currTime, rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    call ESMF_GridCompGet(gridComp, clock=clock, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Allocate the fields for all gridded components and their names
    numGridComp = 9
    allocate(gridCompList(numGridComp))
    allocate(gridCompClockList(numGridComp))
    allocate(gridCompNames(numGridComp))
    allocate(importStates(numGridComp))
    allocate(exportStates(numGridComp))

    gridCompNames(1) = 'getm'
    gridCompNames(2) = 'fabm_pelagic'
    gridCompNames(3) = 'erosed'
    gridCompNames(4) = 'constant'
    gridCompNames(5) = 'fabm_sediment'
    gridCompNames(6) = 'simplewave'
    gridCompNames(7) = 'netcdf'
    gridCompNames(8) = 'clm_netcdf'
    gridCompNames(9) = 'benthos'

    !! Create all gridded components, and create import and export states for these
    call ESMF_GridCompGet(gridComp, vm=vm, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_VmGet(vm, petCount=petCount, rc=rc)
    allocate(petList(petCount))
    do i=1,petCount
      petList(i)=i-1
    enddo

    do i = 1, numGridComp
      gridCompClockList(i) = ESMF_ClockCreate(clock, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    enddo

    gridCompList(1) = ESMF_GridCompCreate(name=trim(gridCompNames(1)),  &
      petList=petList, clock=gridCompClockList(1), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(2) = ESMF_GridCompCreate(name=trim(gridCompNames(2)),  &
      petList=petList, clock=gridCompClockList(2), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(3) = ESMF_GridCompCreate(name=trim(gridCompNames(3)),  &
      petList=petList, clock=gridCompClockList(3), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(4) = ESMF_GridCompCreate(name=trim(gridCompNames(4)),  &
      petList=petList, clock=gridCompClockList(4), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(5) = ESMF_GridCompCreate(name=trim(gridCompNames(5)),  &
      petList=petList, clock=gridCompClockList(5), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(6) = ESMF_GridCompCreate(name=trim(gridCompNames(6)),  &
      petList=petList, clock=gridCompClockList(6), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(7) = ESMF_GridCompCreate(name=trim(gridCompNames(7)),  &
      petList=petList, clock=gridCompClockList(7), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(8) = ESMF_GridCompCreate(name=trim(gridCompNames(8)),  &
      petList=petList, clock=gridCompClockList(8), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    gridCompList(9) = ESMF_GridCompCreate(name=trim(gridCompNames(9)),  &
      petList=petList, clock=gridCompClockList(9), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    do i=1, numGridComp
      exportStates(i) = ESMF_StateCreate(stateintent=ESMF_STATEINTENT_UNSPECIFIED, &
        name=trim(gridCompNames(i))//'ExportState')
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      importStates(i) = ESMF_StateCreate(stateintent=ESMF_STATEINTENT_UNSPECIFIED, &
        name=trim(gridCompNames(i))//'ImportState')
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    enddo

    !! Now register all setServices routines for the gridded components
    call ESMF_GridCompSetServices(gridCompList(1), getm_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(2), fabm_pelagic_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(3), erosed_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(4), constant_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(5), fabm_sediment_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(6), simplewave_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(7), netcdf_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(8), clm_netcdf_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompSetServices(gridCompList(9), benthos_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    !! Allocate the fields for all coupler components and their names
    numCplComp = 3
    allocate(cplCompList(numCplComp))
    allocate(cplCompNames(numCplComp))
    cplCompNames(1) = 'link_coupler'
    cplCompNames(2) = 'benthic_pelagic_coupler'
    cplCompNames(3) = 'pelagic_benthic_coupler'

    do i = 1, numCplComp
      cplCompList(i) = ESMF_CplCompCreate(name=trim(cplCompNames(i)), rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    enddo

    call ESMF_CplCompSetServices(cplCompList(1), link_coupler_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_CplCompSetServices(cplCompList(2), benthic_pelagic_coupler_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_CplCompSetServices(cplCompList(3), pelagic_benthic_coupler_SetServices, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    !! Initialize all components, both cpl and grid components, do this
    !! in the order specified by dependencies/couplings
    !! Also, try to find coupling/dependency specific export/import states in
    !! the initialization

    !! Establish number of phases and zero phase for all components
    !! @> todo this interface will likely change in the future and will
    !! be integrated with GridCompGet

    allocate(hasPhaseZeroList(numGridComp))
    allocate(phaseCountList(numGridComp))

    do i = 1, numGridComp
      call ESMF_GridCompGetEPPhaseCount(gridCompList(i), ESMF_METHOD_INITIALIZE, &
        phaseCount=phaseCount, phaseZeroFlag=hasPhaseZero, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      phaseCountList(i)=phaseCount
      hasPhaseZeroList(i)=hasPhaseZero
    enddo

    !! Go through all phase 0 if components have it
    do i = 1,numGridcomp
      if (.not.hasPhaseZeroList(i)) cycle
      call ESMF_GridCompInitialize(gridCompList(i), exportState=exportStates(i), phase=0, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      !!> @todo expect the Attribute InitializePhaseMap in this state, this attribute
      !! contains information on the phases defined in the component.
    enddo

    !! Go through all phases:
    !! IPDv00p1 = phase 1: Advertise Fields in import and export States. These can be
    !!   empty fields that are later completed with FieldEmptyComplete
    !! IPDv00p2 = phase 2: Realize Fields (that have not been completed in phase 1)

    phase = 1 
    !! Initializing phase 1 of getm
    if (phaseCountList( 1)>=1) then
      call ESMF_GridCompInitialize(gridCompList(1), importState=importStates(1), &
        exportState=exportStates(1), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of fabm_pelagic
    call ESMF_AttributeSet(importStates(2), name="foreign_grid_field_name", value="temperature_in_water", rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    !! Manually added to get grid information from getm to fabm in phase 1
    call ESMF_CplCompInitialize(cplCompList(1), importState=exportStates(1), &
      exportState=importStates(2), clock=clock, phase=1, rc=rc)
    call MOSSCO_StateLog(importStates(2), rc=rc)

    if (phaseCountList( 2)>=1) then
      call ESMF_GridCompInitialize(gridCompList(2), importState=importStates(2), &
        exportState=exportStates(2), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of erosed
    if (phaseCountList( 3)>=1) then
      call ESMF_GridCompInitialize(gridCompList(3), importState=importStates(3), &
        exportState=exportStates(3), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of constant
    if (phaseCountList( 4)>=1) then
      call ESMF_GridCompInitialize(gridCompList(4), importState=importStates(4), &
        exportState=exportStates(4), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of fabm_sediment
    if (phaseCountList( 5)>=1) then
      call ESMF_GridCompInitialize(gridCompList(5), importState=importStates(5), &
        exportState=exportStates(5), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of simplewave
    if (phaseCountList( 6)>=1) then
      call ESMF_GridCompInitialize(gridCompList(6), importState=importStates(6), &
        exportState=exportStates(6), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of netcdf
    if (phaseCountList( 7)>=1) then
      call ESMF_GridCompInitialize(gridCompList(7), importState=importStates(7), &
        exportState=exportStates(7), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of clm_netcdf
    if (phaseCountList( 8)>=1) then
      call ESMF_GridCompInitialize(gridCompList(8), importState=importStates(8), &
        exportState=exportStates(8), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 1 of benthos
    if (phaseCountList( 9)>=1) then
      call ESMF_GridCompInitialize(gridCompList(9), importState=importStates(9), &
        exportState=exportStates(9), clock=clock, phase=1, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing link_coupler
    call ESMF_CplCompInitialize(cplCompList(1), importState=exportStates(8), &
      exportState=importStates(1), clock=clock, phase=1, rc=rc)

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing benthic_pelagic_coupler
    call ESMF_CplCompInitialize(cplCompList(2), importState=exportStates(5), &
      exportState=importStates(2), clock=clock, phase=1, rc=rc)

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing pelagic_benthic_coupler
    call ESMF_CplCompInitialize(cplCompList(3), importState=exportStates(2), &
      exportState=importStates(5), clock=clock, phase=1, rc=rc)

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    phase = 2 
    !! Initializing phase 2 of getm
    if (phaseCountList( 1)>=2) then
      call ESMF_GridCompInitialize(gridCompList(1), importState=importStates(1), &
        exportState=exportStates(1), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of fabm_pelagic
    if (phaseCountList( 2)>=2) then
      call ESMF_GridCompInitialize(gridCompList(2), importState=importStates(2), &
        exportState=exportStates(2), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of erosed
    if (phaseCountList( 3)>=2) then
      call ESMF_GridCompInitialize(gridCompList(3), importState=importStates(3), &
        exportState=exportStates(3), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of constant
    if (phaseCountList( 4)>=2) then
      call ESMF_GridCompInitialize(gridCompList(4), importState=importStates(4), &
        exportState=exportStates(4), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of fabm_sediment
    if (phaseCountList( 5)>=2) then
      call ESMF_GridCompInitialize(gridCompList(5), importState=importStates(5), &
        exportState=exportStates(5), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of simplewave
    if (phaseCountList( 6)>=2) then
      call ESMF_GridCompInitialize(gridCompList(6), importState=importStates(6), &
        exportState=exportStates(6), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of netcdf
    if (phaseCountList( 7)>=2) then
      call ESMF_GridCompInitialize(gridCompList(7), importState=importStates(7), &
        exportState=exportStates(7), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of clm_netcdf
    if (phaseCountList( 8)>=2) then
      call ESMF_GridCompInitialize(gridCompList(8), importState=importStates(8), &
        exportState=exportStates(8), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing phase 2 of benthos
    if (phaseCountList( 9)>=2) then
      call ESMF_GridCompInitialize(gridCompList(9), importState=importStates(9), &
        exportState=exportStates(9), clock=clock, phase=2, rc=rc)
    endif

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing link_coupler
    call ESMF_CplCompInitialize(cplCompList(1), importState=exportStates(8), &
      exportState=importStates(1), clock=clock, phase=2, rc=rc)

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing benthic_pelagic_coupler
    call ESMF_CplCompInitialize(cplCompList(2), importState=exportStates(5), &
      exportState=importStates(2), clock=clock, phase=2, rc=rc)

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    !! Initializing pelagic_benthic_coupler
    call ESMF_CplCompInitialize(cplCompList(3), importState=exportStates(2), &
      exportState=importStates(5), clock=clock, phase=2, rc=rc)

    if (rc /= ESMF_SUCCESS) then
      if ((rc == ESMF_RC_ARG_SAMECOMM .or. rc==506) .and. phase>1) then
        write(message,'(A,I4)') 'There is no initialization defined for phase=', phase
        write(message,'(A,A)') trim(message),' For now, ignore errors  immediately above'
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_WARNING)
      else
        write(message,'(A,I4)') 'Initializing failed with error code ', rc
        call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
        call ESMF_LogFlush()
        call ESMF_Finalize(endflag=ESMF_END_ABORT)
      endif
    endif
    numCplAlarm = 15
    if (.not.allocated(cplAlarmList)) allocate(cplAlarmList(numCplAlarm))
    if (.not.allocated(cplNames)) allocate(cplNames(numCplAlarm))
    cplNames(:) = 'link'
    cplNames(9)='pelagic_benthic'
    cplNames(13)='benthic_pelagic'

    !! Set the coupling alarm starting from start time of local clock
    call ESMF_ClockGet(clock,startTime=startTime, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(1)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='clm_netcdf--getm--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='clm_netcdf' .or. trim(name)=='getm') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(1), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(2)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='getm--simplewave--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='getm' .or. trim(name)=='simplewave') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(2), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(3)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='clm_netcdf--simplewave--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='clm_netcdf' .or. trim(name)=='simplewave') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(3), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(4)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='simplewave--erosed--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='simplewave' .or. trim(name)=='erosed') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(4), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(5)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='getm--fabm_pelagic--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='getm' .or. trim(name)=='fabm_pelagic') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(5), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(6)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='fabm_pelagic--erosed--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='fabm_pelagic' .or. trim(name)=='erosed') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(6), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(7)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='getm--erosed--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='getm' .or. trim(name)=='erosed') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(7), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(8)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='erosed--fabm_pelagic--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='erosed' .or. trim(name)=='fabm_pelagic') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(8), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(9)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='fabm_pelagic--fabm_sediment--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='fabm_pelagic' .or. trim(name)=='fabm_sediment') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(9), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, yy=1 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(10)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='constant--fabm_sediment--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='constant' .or. trim(name)=='fabm_sediment') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(10), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, d=1 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(11)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='fabm_sediment--netcdf--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='fabm_sediment' .or. trim(name)=='netcdf') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(11), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, h=1 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(12)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='erosed--netcdf--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='erosed' .or. trim(name)=='netcdf') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(12), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, m=6 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(13)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='fabm_sediment--fabm_pelagic--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='fabm_sediment' .or. trim(name)=='fabm_pelagic') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(13), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, h=1 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(14)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='benthos--erosed--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='benthos' .or. trim(name)=='erosed') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(14), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
        call ESMF_TimeIntervalSet(alarmInterval, startTime, h=1 ,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    cplAlarmList(15)=ESMF_AlarmCreate(clock=clock,ringTime=startTime+alarmInterval, &
      ringInterval=alarmInterval, name='fabm_sediment--benthos--cplAlarm', rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Copy this alarm to all children as well
    do i=1,numGridComp
      call ESMF_GridCompGet(gridCompList(i),name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (trim(name)=='fabm_sediment' .or. trim(name)=='benthos') then
        call ESMF_GridCompGet(gridCompList(i), clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (clockIsPresent) then
          call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        else
          call ESMF_LOGWRITE('Creating clock for '//trim(name)//', this should have been done by the component.', &
            ESMF_LOGMSG_WARNING)

          childClock=ESMF_ClockCreate(clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_GridCompSet(gridCompList(i),clock=childClock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif
        childAlarm=ESMF_AlarmCreate(cplAlarmList(15), rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmSet(childAlarm, clock=childClock)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      endif
    enddo
    
    !! Set the default ringTime to the stopTime of local clock, then get all Alarms
    !! from local clock into alarmList, find those that contain the string "cplAlarm"
    !! and look for the earliest ringtime in all coupling alarms.  Save that in the
    !! ringTime
    call ESMF_ClockGet(clock, stopTime=ringTime, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    call ESMF_ClockGetAlarmList(clock,ESMF_ALARMLIST_ALL,alarmCount=alarmCount,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
    if (.not.allocated(alarmList)) allocate(alarmList(alarmCount))
    call ESMF_ClockGetAlarmList(clock,ESMF_ALARMLIST_ALL,alarmList=alarmList,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    do i=1,ubound(alarmList,1)
      call ESMF_AlarmGet(alarmList(i), ringTime=time, name=name, rc=rc)

      call ESMF_TimeGet(time,timeStringISOFrac=timestring)
      write(message,'(A)') trim(name)//' rings at '//trim(timestring)
      call ESMF_LogWrite(trim(message), ESMF_LOGMSG_INFO)

      if (index(trim(name),'cplAlarm') < 1) cycle
      if (time<ringTime) ringTime=time
    enddo
    if (allocated(alarmList)) deallocate(alarmList)

    !! Set the timestep such that it corresponds to the time until the
    !! first ringing alarm, log that time
    call ESMF_ClockGet(clock,currTime=currTime,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
    call ESMF_ClockSet(clock,timeStep=ringTime-currTime,rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    call ESMF_GridCompGet(gridComp, name=name, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    call ESMF_TimeGet(ringTime,timeStringISOFrac=timestring, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
    write(message,'(A)') trim(name)//' alarms ring next at '//trim(timestring)
    call ESMF_LogWrite(trim(message), ESMF_LOGMSG_INFO)

    call MOSSCO_CompExit(gridComp, rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Flush the log at the end of Initialize()
    call ESMF_LogFlush(rc=rc)

  end subroutine Initialize

  subroutine Run(gridComp, importState, exportState, parentClock, rc)

    type(ESMF_GridComp)  :: gridComp
    type(ESMF_State)     :: importState, exportState
    type(ESMF_Clock)     :: parentClock
    integer, intent(out) :: rc

    character(len=ESMF_MAXSTR) :: timestring, cplName, myName
    type(ESMF_Time)            :: stopTime, currTime, ringTime, time
    type(ESMF_TimeInterval)    :: timeInterval, ringInterval
    integer(ESMF_KIND_I8)      :: advanceCount,  i, j, k, l
    integer(ESMF_KIND_I4)      :: alarmCount, petCount, localPet
    integer(ESMF_KIND_I4)      :: numGridComp, numCplComp
    integer(ESMF_KIND_I4)      :: hours, minutes, seconds

    type(ESMF_Alarm), dimension(:), allocatable :: alarmList
    type(ESMF_Alarm)        :: childAlarm
    type(ESMF_Clock)        :: childClock, clock
    logical                 :: clockIsPresent
    type(ESMF_State)        :: impState, expState
    type(ESMF_Field)        :: field
    type(ESMF_FieldBundle)  :: fieldBundle
    type(ESMF_Array)        :: array
    type(ESMF_ArrayBundle)  :: arrayBundle
    type(ESMF_StateItem_Flag), dimension(:), allocatable :: itemTypeList
    character(len=ESMF_MAXSTR), dimension(:), allocatable:: itemNameList
    integer                  :: itemCount

    character(len=ESMF_MAXSTR) :: message, compName, name, alarmName, otherName

    integer(ESMF_KIND_I4)  :: phase, phaseCount
    integer(ESMF_KIND_I4), dimension(:), allocatable :: phaseCountList
    logical, allocatable   :: hasPhaseZeroList(:)
    logical                :: hasPhaseZero
    integer(ESMF_KIND_I4), parameter :: maxPhaseCount=9

    call MOSSCO_CompEntry(gridComp, parentClock, name, currTime, rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    call ESMF_GridCompGet(gridComp, clock=clock, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    if (.not.allocated(alarmList)) allocate(alarmList(20))

    numGridComp=ubound(gridCompList,1)-lbound(gridCompList,1)+1

    !! Establish number of phases and zero phase for all components
    !! @> todo this interface will likely change in the future and will
    !! be integrated with GridCompGet

    allocate(hasPhaseZeroList(numGridComp))
    allocate(phaseCountList(numGridComp))

    do i = 1, numGridComp
      call ESMF_GridCompGetEPPhaseCount(gridCompList(i), ESMF_METHOD_RUN, &
        phaseCount=phaseCount, phaseZeroFlag=hasPhaseZero, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      phaseCountList(i)=phaseCount
      hasPhaseZeroList(i)=hasPhaseZero
    enddo

    call ESMF_ClockGetAlarmList(clock, alarmListFlag=ESMF_ALARMLIST_ALL, &
      alarmCount=alarmCount, rc=rc)

    if (allocated(alarmList)) then
      if (size(alarmList)<alarmCount) then
        deallocate(alarmList)
        allocate(alarmList(alarmCount))
      endif
    else
      allocate(alarmList(alarmCount))
    endif

    !! Run until the clock's stoptime is reached
    do

      call ESMF_ClockGet(clock,currTime=currTime, stopTime=stopTime, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

      if (currTime>stopTime) then
        call ESMF_LogWrite('Clock out of scope in '//trim(compName), ESMF_LOGMSG_ERROR)
        call ESMF_FINALIZE(endflag=ESMF_END_ABORT, rc=rc)
      endif

      !! Loop through all components and check whether their clock is currently at the
      !! same time as my own clock's currTime, if yes, then run the respective couplers
      do i=1,numGridComp
        !! Determine for each child the clock
        call ESMF_GridCompGet(gridCompList(i),name=compName, clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (.not.clockIsPresent) then
          call ESMF_LogWrite('Required clock not found in '//trim(compName), ESMF_LOGMSG_ERROR)
          call ESMF_FINALIZE(endflag=ESMF_END_ABORT, rc=rc)
        endif

        call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_ClockGet(childClock,currTime=time, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

        ! write(message,'(A)') trim(compName)//' now at '//trim(timestring)
        !  call ESMF_LogWrite(trim(message),ESMF_LOGMSG_TRACE)

        if (time>currTime) cycle

        !! Find all the alarms in this child and call all the couplers that
        !! have ringing alarms at this stage

        call ESMF_ClockGetAlarmList(childClock, alarmListFlag=ESMF_ALARMLIST_ALL, &
          alarmCount=alarmCount, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (alarmCount>ubound(alarmList,1)) then
          deallocate(alarmList)
          allocate(alarmList(alarmCount))
        endif

        if (alarmCount==0) then
          timeInterval=stopTime-currTime
          !call ESMF_LogWrite(trim(compName)//' has not ringing alarm at '//trim(timestring),ESMF_LOGMSG_WARNING)
        else
          call ESMF_ClockGetAlarmList(childClock, alarmListFlag=ESMF_ALARMLIST_ALL, &
             alarmList=alarmList, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif

        do j=1,alarmCount
          call ESMF_AlarmGet(alarmList(j), name=alarmName, ringTime=ringTime, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          !! Skip this alarm if it is not a cplAlarm
          if (index(trim(alarmName),'cplAlarm') < 1) cycle

          !! Skip this alarm if it is inbound of this component
          if (trim(alarmName(1:index(alarmName,'--')-1))/=trim(compName)) cycle

          !! Skip this alarm if it is not ringing now
          !if (ringTime > currTime) cycle

          call ESMF_TimeGet(ringTime,timeStringISOFrac=timeString)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

          !write(0,*) trim(compName)//' ', i,'/',alarmCount,' '//trim(alarmName)//' rings at '//trim(timeString)
          write(message,'(A)') trim(compName)//' '//trim(alarmName)//' rings at '//trim(timeString)
          call ESMF_LogWrite(trim(message), ESMF_LOGMSG_TRACE)

          myName=trim(alarmName(1:index(alarmName,'--')-1))
          otherName=trim(alarmName(index(alarmName,'--')+2:index(alarmName,'--cplAlarm')-1))

          do k=1,ubound(cplAlarmList,1)
            if (cplAlarmList(k) == alarmList(j)) then
              cplName = trim(cplNames(k))
              exit
            endif
          enddo

          write(message,'(A)') trim(timeString)//' '//trim(myName)//' ->'
          if (trim(cplName) /= 'link') then
            write(message,'(A)') trim(message)//' '//trim(cplName)//' ->'
          else
            write(message,'(A)') trim(message)//' ('//trim(cplName)//') ->'
          endif
          write(message,'(A)') trim(message)//' '//trim(otherName)
          call ESMF_LogWrite(trim(message), ESMF_LOGMSG_TRACE)

          call ESMF_GridCompGet(gridCompList(i), exportState=impState, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          !! Search the gridCompList for other's name
          do k=1, ubound(gridCompList,1)
              call ESMF_GridCompGet(gridCompList(k), name=name, rc=rc)
              if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
              if (trim(name)==trim(otherName)) exit
          enddo

          if (trim(name) /= trim(otherName)) then
            write(message,'(A)') 'Did not find component '//trim(otherName)
            call ESMF_LogWrite(trim(message), ESMF_LOGMSG_ERROR)
            call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
          endif

          !! Search the cplCompList for cplName
          do l=1, ubound(cplCompNames,1)
              !write(0,*) l,trim(cplCompNames(l))//' ?= '//trim(cplName)//'_coupler'
              if (trim(cplCompNames(l))==trim(cplName)//'_coupler') exit
          enddo

          call ESMF_GridCompGet(gridCompList(k), importState=expState, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          call ESMF_TimeGet(currTime,timeStringISOFrac=timeString)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
          write(message,'(A)') trim(timeString)//' Calling '//trim(cplCompNames(l))
          call ESMF_LogWrite(trim(message), ESMF_LOGMSG_TRACE)

          call ESMF_CplCompRun(cplCompList(l), importState=impState, &
            exportState=expState, clock=clock, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        enddo
      enddo

      !! Loop through all components and check whether their clock is currently at the
      !! same time as my own clock's currTime, if yes, then run the component
      do i=1,numGridComp
        !! Determine for each child the clock
        call ESMF_GridCompGet(gridCompList(i),name=compName, clockIsPresent=clockIsPresent, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (.not.clockIsPresent) then
          call ESMF_LogWrite('Required clock not found in '//trim(compName), ESMF_LOGMSG_ERROR)
          call ESMF_FINALIZE(endflag=ESMF_END_ABORT, rc=rc)
        endif

        call ESMF_GridCompGet(gridCompList(i), clock=childClock, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_ClockGet(childClock,currTime=time, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
        call ESMF_TimeGet(time,timeStringISOFrac=timeString)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

        if (time>currTime) then
          call ESMF_TimeGet(time,timeStringISOFrac=timeString)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
          write(message,'(A)') trim(compName)//' now at '//trim(timestring)//', but'
          call ESMF_LogWrite(trim(message),ESMF_LOGMSG_WARNING)

          call ESMF_TimeGet(currTime,timeStringISOFrac=timeString)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
          write(message,'(A)') trim(name)//' now at '//trim(timestring)//', cycling ...'
          call ESMF_LogWrite(trim(message),ESMF_LOGMSG_WARNING)

          cycle
        endif

        !! Find the child's alarm list, get the interval to the next ringing alarm
        !! and run the component for the interval until that alarm

        call ESMF_ClockGetAlarmList(childClock, alarmListFlag=ESMF_ALARMLIST_ALL, &
          alarmCount=alarmCount, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        if (alarmCount==0) then
          !call ESMF_LogWrite('No alarm found in '//trim(compName), ESMF_LOGMSG_WARNING)
          timeInterval=stopTime-currTime
        else
          call ESMF_ClockGetAlarmList(childClock, alarmListFlag=ESMF_ALARMLIST_ALL, &
             alarmList=alarmList, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif

        !! Set the default ringTime to the stopTime of local clock, then get all Alarms
        !! from local clock into alarmList, find those that contain the string "cplAlarm"
        !! and look for the earliest ringtime in all coupling alarms.  Save that in the
        !! ringTime
        call ESMF_ClockGet(clock, stopTime=ringTime, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        do j=1,alarmCount
          call ESMF_AlarmGet(alarmList(j), name=alarmName, ringTime=time, &
            ringInterval=ringInterval, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
          if (index(trim(alarmName),'cplAlarm')<1) cycle

          if (time==currTime) ringTime=currTime+ringInterval
          if (time<ringTime) ringTime=time
        enddo

        !call ESMF_TimeGet(ringTime,timeStringISOFrac=timestring, rc=rc)
        !if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        !write(message,'(A)') 'Setting child''s stopTime to'//trim(timeString)
        !call ESMF_LogWrite(trim(message),ESMF_LOGMSG_TRACE, rc=rc);


        call ESMF_ClockSet(childClock, stopTime=ringTime, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

        call ESMF_ClockGet(childClock, timeStep=timeInterval, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        if (timeInterval>ringTime-currTime) then
          call ESMF_ClockSet(childClock, timeStep=ringTime-currTime, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
        endif

        timeInterval=ringTime-currTime

        call ESMF_TimeIntervalGet(timeInterval, h=hours, m=minutes, s=seconds, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

        write(message,'(A,A,I5.5,A,I2.2,A,I2.2,A)') trim(timeString)//' calling '//trim(compName), &
          ' to run for ', hours, ':', minutes, ':', seconds, ' hours'
        call ESMF_LogWrite(trim(message),ESMF_LOGMSG_TRACE, rc=rc);

        !! Loop over all run phases, disregarding any action that could be taken between
        !! phases
        do phase=1,phaseCountList(i)
          call ESMF_GridCompRun(gridCompList(i),importState=importStates(i),&
            exportState=exportStates(i), clock=clock, phase=phase, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
        enddo

        call ESMF_ClockGet(childClock, currTime=time, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

        if (time == currTime) then
          !! This child component did not advance its clock in its Run() routine
          !! We do that here
          call ESMF_LogWrite(trim(compName)//' did not advance its clock',ESMF_LOGMSG_WARNING)

          call ESMF_ClockAdvance(childClock, timeStep=timeInterval, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
        endif
      enddo

      !! Now that all child components have been started, find out the minimum time
      !! to the next coupling and use this as a time step for my own clock Advance
      call ESMF_GridCompGet(gridComp, name=name, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      call ESMF_ClockGetAlarmList(clock, alarmListFlag=ESMF_ALARMLIST_ALL, &
        alarmCount=alarmCount, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

      if (alarmCount==0) then
        !call ESMF_LogWrite('No alarm found in '//trim(name), ESMF_LOGMSG_WARNING)
        timeInterval=stopTime-currTime
      else
        call ESMF_ClockGetAlarmList(clock, alarmListFlag=ESMF_ALARMLIST_ALL, &
          alarmList=alarmList, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        call ESMF_AlarmGet(alarmList(1), ringTime=ringTime, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

        do j=2,alarmCount
          call ESMF_AlarmGet(alarmList(j), ringTime=time, rc=rc)
          if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

          if (time<ringTime) ringTime=time
        enddo

        timeInterval=ringTime-currTime
      endif

      !> Log current and next ring time
      call ESMF_TimeGet(currTime,timeStringISOFrac=timestring, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
      write(message,'(A)') trim(timeString)//' '//trim(name)//' stepping to'
      call ESMF_TimeGet(ringTime,timeStringISOFrac=timestring, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)
      write(message,'(A)') trim(message)//' '//trim(timeString)
      call ESMF_LogWrite(trim(message),ESMF_LOGMSG_TRACE, rc=rc);

      !> Set new time interval and advance clock, stop if end of
      !! simulation reached
      call ESMF_ClockSet(clock, timeStep=timeInterval, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      call ESMF_ClockAdvance(clock, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      if (ESMF_ClockIsStopTime(clock, rc=rc)) exit
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    enddo

    call MOSSCO_CompExit(gridComp, rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  end subroutine Run

  subroutine Finalize(gridComp, importState, exportState, parentClock, rc)
    type(ESMF_GridComp)  :: gridComp
    type(ESMF_State)     :: importState, exportState
    type(ESMF_Clock)     :: parentClock
    integer, intent(out) :: rc

    integer(ESMF_KIND_I8)   :: i
    integer(ESMF_KIND_I4)   :: petCount, localPet,numGridComp, numCplComp
    character(ESMF_MAXSTR)  :: name, message, timeString
    logical                 :: clockIsPresent
    type(ESMF_Time)         :: currTime
    type(ESMF_Clock)        :: clock

    integer(ESMF_KIND_I4)  :: phase, phaseCount
    integer(ESMF_KIND_I4), dimension(:), allocatable :: phaseCountList
    logical, allocatable   :: hasPhaseZeroList(:)
    logical                :: hasPhaseZero
    integer(ESMF_KIND_I4), parameter :: maxPhaseCount=9

    call MOSSCO_CompEntry(gridComp, parentClock, name, currTime, rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    call ESMF_GridCompGet(gridComp, clock=clock, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

    !! Establish number of phases and zero phase for all components
    !! @> todo this interface will likely change in the future and will
    !! be integrated with GridCompGet

    numGridComp=size(gridCompList)

    allocate(hasPhaseZeroList(numGridComp))
    allocate(phaseCountList(numGridComp))

    do i = 1, numGridComp
      call ESMF_GridCompGetEPPhaseCount(gridCompList(i), ESMF_METHOD_FINALIZE, &
        phaseCount=phaseCount, phaseZeroFlag=hasPhaseZero, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      phaseCountList(i)=phaseCount
      hasPhaseZeroList(i)=hasPhaseZero
    enddo

    do i=1,ubound(cplCompList,1)
      call ESMF_CplCompFinalize(cplCompList(i), clock=clock, rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    enddo
    do i=1,ubound(gridCompList,1)
      do phase=1,phaseCountList(i)
        call ESMF_GridCompFinalize(gridCompList(i), clock=clock, phase=phase, rc=rc)
        if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      enddo
    enddo
    do i=1,ubound(gridCompList,1)
      !!@todo destroy any remaining fields/arrays in states
      call ESMF_StateDestroy(exportStates(i), rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
      call ESMF_StateDestroy(importStates(i), rc=rc)
      if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    enddo

    call ESMF_GridCompDestroy(gridCompList(1), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(2), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(3), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(4), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(5), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(6), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(7), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(8), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_GridCompDestroy(gridCompList(9), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_CplCompDestroy(cplCompList(1), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_CplCompDestroy(cplCompList(2), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)
    call ESMF_CplCompDestroy(cplCompList(3), rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    if (allocated(gridCompClockList)) deallocate(gridCompClockList)
    if (allocated(gridCompList)) deallocate(gridCompList)
    if (allocated(cplCompList))  deallocate(cplCompList)
    if (allocated(exportStates)) deallocate(exportStates)
    if (allocated(importStates)) deallocate(importStates)
    if (allocated(cplAlarmList)) deallocate(cplAlarmList)

    call ESMF_ClockDestroy(clock, rc=rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT)

    call MOSSCO_CompExit(gridComp, rc)
    if (rc /= ESMF_SUCCESS) call ESMF_Finalize(endflag=ESMF_END_ABORT, rc=rc)

  end subroutine Finalize

end module toplevel_component
