#!/bin/bash
#
# This script  is part of MOSSCO.  It tailors big netcdf files to relevant eco-variables
#
# @copyright (C) 2015 Helmholtz-Zentrum Geesthacht
# @author Kai W. Wirtz
# @author Carsten Lemmen
#
# MOSSCO is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License v3+.  MOSSCO is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY.  Consult the file
# LICENSE.GPL or www.gnu.org/licenses/gpl-3.0.txt for the full license terms.
#

# ---------------------
# User configuration
# Declare a list of variables to extract
declare -a vn=("Phytplankton_Carbon_phyC_in_water" "Phytplankton_Nitrogen_phyN_in_water" "Phytplankton_Phosphorus_phyP_in_water" "Dissolved_Inorganic_Phosphorus_DIP_nutP_in_water" "Dissolved_Inorganic_Nitrogen_DIN_nutN_in_water"   "Detritus_Carbon_detC_in_water" "Chl_chl_in_water" "temperature_in_water" "mole_concentration_of_nitrate_in_soil" ) 
#declare -a vn=("denitrification_rate_in_soil" "mole_concentration_of_nitrate_in_soil" "dissolved_oxygen_in_soil")
#"temperature_in_water" "water_depth_at_soil_surface" "Detritus_Nitrogen_detN_in_water"  "Chl_chl_in_water" 
#declare -a vn=( "fast_detritus_C_in_soil"   "nutrients_in_water" "phytoplankton_in_water" "detritus_in_water" )

#"chl" "Rub" "Chl_chl_in_water"
# 
model=''   # Fabm model name, e.g. hzg_maecs

if [ $# -ne 2 ]; then
  outdir=~/ocean/data/cut    # Where to put the extracted files
else
  outdir=$2
fi

#prefix=netcdf_getm_fabm_pelagic.  # Prefix of files to process
prefix=mossco_gffrn.  # Prefix of files to process
dt=3          # slicing of time dimension
dlat=1        # slicing of lat dimension
dlon=1        # slicing of lon dimension
dz=28          # slicing of vertical dimension
# ---------------------
# Needs number of processors  as argument

if [[ "x$1" == "x" ]] ; then
  echo "This script needs the number of processors as input argument."
  echo "Provide 0 if you do not want to process multiprocessor output."
  exit 1
else
  nproc=$(expr $1 - 1)
fi



mkdir -p $outdir

# build comma separated string
ts=$model${vn[0]}
for (( i=1; i<${#vn[@]}; i++ )) do
  ts=$ts','$model${vn[$i]}
done # i
echo $ts

if [[ $nproc == -1 ]]; then
  fname=${prefix}'.nc'
  if ! test -f $fname ; then
    echo "File $fname does not exist"
    exit 1
  fi
  outname=$outdir'/cut.nc'
  echo $fname '->' $outname
  # invokes nco tool and writes output to folder "cut/"
  #   skipping every 2nd lateral grid point and output-time step
  ncks -O -v time,getmGrid2D_getm_lat,getmGrid2D_getm_lon,getmGrid3D_getm_lat,getmGrid3D_getm_lon,$ts\
    -d getmGrid2D_getm_1,1,,${dlon} \
    -d getmGrid2D_getm_2,1,,${dlat} \
    -d getmGrid3D_getm_1,1,,${dlon} \
    -d getmGrid3D_getm_2,1,,${dlat} \
    -d time,820,836,${dt} $fname $outname
#2367000,2412000
  # compares file sizes
  ls -l  $fname $outname
else
	# loop over all nc files generated by mossco for multiprocessor output
	for p in $(seq -f "%02g" 0 $nproc); do
		fname=${prefix}$p'.nc'
    if ! [[ -f $fname ]] ; then
      echo "File $fname does not exist"
      exit 1
    fi

		outname=$outdir'/cut_'$p'.nc'
		echo $fname '->' $outname
		# invokes nco tool and writes output to folder "cut/"
#			-d getmGrid3D_getm_3,1,,${dz} \
#			-d ungridded00024,1,,23 \
		ncks -O -v time,getmGrid2D_getm_lat,getmGrid2D_getm_lon,getmGrid3D_getm_lat,getmGrid3D_getm_lon,$ts\
			-d getmGrid2D_getm_1,1,,${dlon} \
			-d getmGrid2D_getm_2,1,,${dlat} \
			-d getmGrid3D_getm_1,1,,${dlon} \
			-d getmGrid3D_getm_2,1,,${dlat} \
			-d getmGrid3D_getm_3,1,,${dz} \
			-d time,10,,${dt} $fname $outname
		ls -l  $fname $outname
	done
fi
