# This workflow definition is part of MOSSCO
#
# @copyright (C) 2019 Helmholtz-Zentrum Geesthacht
# @author Carsten Lemmen <carsten.lemmen@hzg.de>
#
# MOSSCO is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License v3+.  MOSSCO is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY.  Consult the file
# LICENSE.GPL or www.gnu.org/licenses/gpl-3.0.txt for the full license terms.
#

name: install-externals
on:
  - push
#  - schedule:
#    - cron:  '5 23 * * *' # minute hour day month year, so each day at 23:05

jobs:
  download-esmf-job:
    name: Download and build ESMF
    runs-on: ubuntu-latest
    env:
      ESMF_DIR: ${HOME}/opt/devel/esmf
      ESMF_INSTALL_PREFIX: ${HOME}/opt
    steps:
      - name: Clean ESMF directory
        run:
          - mkdir -p ${ESMF_DIR}/..
          - rm -rf ${ESMF_DIR}
      - name: Clone ESMF
        run:
          git clone --shallow git://esmf.git.sourceforge.net/gitroot/esmf/esmf ${ESMF_DIR}
      - name: Build ESMF
        env:
          ESMF_BOPT: O
          ESMF_COMM: mpiuni
          # @todo ESMF variable specification
        run:
          - cd ${ESMF_DIR}
          - make esmflib
          - make install
  checkout-externals-job:
      name: Checkout externals
      runs-on: ubuntu-latest
      env:
        MOSSCO_DIR: ${HOME}/devel/mossco-code
      steps:
#        - name: Setup debug for actions
#          uses: hmarr/debug-action@v1
        - name: Checkout yourself with action
          uses: actions/checkout@v1
          with:
            fetch-depth: 1
        - name: Checkout yourself manually
          run:
            - rm -rf ${MOSSCO_DIR}/*
            - git clone --depth=1 ${GITHUB_REPOSITORY} ${MOSSCO_DIR}
        - name: Checkout gotm
          run: make -C ${MOSSCO_DIR}/external gotm
        - name: Checkout getm
          run: make -C ${MOSSCO_DIR}/external getm
        - name: Checkout fabm
          run: make -C ${MOSSCO_DIR}/external fabm
        - name: Update all
          run: make -C {MOSSCO_DIR} external
